# Generated by Django 4.1.11 on 2023-12-23 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("position", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "application_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "resume_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "cover_letter_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=10000, null=True),
                ),
                ("status", models.CharField(max_length=255)),
                ("date_applied", models.DateTimeField(blank=True, null=True)),
                ("date_edited", models.DateTimeField(blank=True)),
                ("date_created", models.DateTimeField(blank=True)),
                ("salary", models.CharField(max_length=255)),
                ("salary_rate", models.CharField(max_length=255)),
                ("archived", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="app_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("task_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("date_due", models.DateTimeField()),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("date_edited", models.DateTimeField(blank=True)),
                ("date_created", models.DateTimeField(blank=True)),
                ("archived", models.BooleanField(default=False)),
                ("last_archived", models.BooleanField(default=False)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="trackerapp.application",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notes",
            fields=[
                ("note_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField()),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("note", models.CharField(blank=True, max_length=2048, null=True)),
                ("archived", models.BooleanField(default=False)),
                ("last_archived", models.BooleanField(default=False)),
                ("date_edited", models.DateTimeField(blank=True)),
                ("date_created", models.DateTimeField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="trackerapp.application",
                    ),
                ),
            ],
        ),
    ]
