# Generated by Django 4.1.9 on 2023-06-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trackerapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="application_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="cover_letter_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="resume_link",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
