# Generated by Django 3.1 on 2023-05-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('position', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('interview_preparation', models.CharField(blank=True, max_length=255, null=True)),
                ('resume_link', models.CharField(blank=True, max_length=255, null=True)),
                ('cover_letter_link', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=2048)),
                ('status', models.CharField(max_length=255)),
                ('date_applied', models.CharField(blank=True, max_length=255, null=True)),
                ('date_edited', models.CharField(max_length=255)),
                ('date_created', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('date_due', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
